### ISSUE TITLE
Icon not readable with dark mode

### ISSUE THREAD

**Issue by justeepin** [AndroidLabs-org/AppListBackup#14]
The app icon is not readable if the phone is using dark mode (see attached screenshot).

![Screenshot_20240814-065550.png](https://github.com/user-attachments/assets/49bc4aa3-31d9-494b-95e5-81197c85989b)

**Comment by AndroidLabs-org** [comment]
Hi there!
Thank you for your proposal. This has been implemented and will be included in the next release.
