### ISSUE TITLE
[Feature suggestion] Add origin of the app - F-droid, Playstore etc

### ISSUE THREAD

**Issue by jarofromel** [AndroidLabs-org/AppListBackup#22]
Hello, thanks for the useful application.

I suggest to add the field with the origin of installation. I have on my phone apps installed from Playstore, F-droid, Samsung store and it would be very nice to see this information in the output of AppListBackup.

I don't know if this information is easily available from the Android system, if it is complicated, feel free to close this issue.

**Comment by AndroidLabs-org** [comment]
Hi there!
Thank you for your proposal. This has been implemented and will be included in the next release.
