### ISSUE TITLE
Disabled Apps Not Listed

### ISSUE THREAD

**Issue by palmuse** [AndroidLabs-org/AppListBackup#4]
I have many apps disabled via the Hail app. None of these disabled apps appear in my list. Tjey do appear in my settings under disabled apps so it seems they are searchable.

OS version: 14
Bootloader: unknown, VM: ART
Kernel: 5.15.123-android13-8-00759-g1e27f4e0fc91
Brand: OnePlus, Model: CPH2451
Board: kalama, Manufacturer: OnePlus

Hail working mode: Shizuku

Great idea. Appreciate your efforts.

**Comment by AndroidLabs-org** [comment]
Hi!
Could you write what working mode is used in Hail settings?

**Comment by palmuse** [comment]
Hail working mode: Shizuku

**Comment by AndroidLabs-org** [comment]
The fix will be published soon
Thank you for report

**Comment by palmuse** [comment]
I am still not seeing my disabled apps in the list.
