### ISSUE TITLE
Add some more details in readme?

### ISSUE THREAD

**Issue by GfEW** [AndroidLabs-org/AppListBackup#8]
First off, this new backup solution sounds like exciting news nowadays where adb backup, and everything based on it, ceases to be functional.

However I wonder:
* Does AppListBackup require anything like root, Shizuku, adb?
* What can it do without?
* Does it backup/restore split apps correctly?

I don't mean this issue to answer these questions here, but rather to suggest briefly addressing them in the readme, so people know what to expect without installing an app that might not be usable on their devices anyway (e. g. due to lack of required root).

Thanks a lot for your effort!

**Comment by AndroidLabs-org** [comment]
The first version was not accurate enough and we have updated the metadata.

Thanks for the report.
